### ISSUE TITLE
can not reproduce the reported performance

### ISSUE THREAD

**Issue by ML-Song** [JiechaoGuan/FSL-DAPNA#1]

**Comment by ML-Song** [comment]
Besides, i'm trying to reproduce the results of PN in figure 2.
It seems that with only PN the model can reach 82% on miniImagenet. 
This has outperformed most algorithm, it's there any tricks to train a PN?
I use this command to reproduce the results of PN
`python train.py --lambda_pre_fsl_loss 1 --lambda_da 0 --lambda_new_fsl_loss 0 --proto_attention 0 --gpu 0 --dataset 'MiniImageNet' --model_type 'ResNet' --init_weights './MiniImageNet-ResNet-Pre/0.001_0.1/model_best.pth.tar'`
However, i only get Test Acc 0.4485 + 0.0016

**Comment by ML-Song** [comment]
I also evaluated the performance with the checkpoint you provided.
By running `python eval.py --base_net_path saves/mini_wideresnet28_best.pth.tar`, i get Test Acc 0.8182 + 0.0038 which is lower than the reported performance.

**Comment by ML-Song** [comment]
By running
--Standard FSL Setting
1. Pre-train and save a model.
  -- python pretrain.py
2. Train a DAPNA model.
  -- sh train_proto_mdd.sh
3. Evaluate DAPNA's performance.
  -- python eval.py

Test Acc 0.6273 + 0.0039

**Comment by JiechaoGuan** [comment]
Thanks for pointing this out. I need to clarify that the pretrained model we use in our experiments is trained on Place365 dataset, which does not have the overlap classes with that of 3 public FSL benchmarks (MiniImageNet/TieredImageNet/CUB). We have released our pretrained model at the begining, and now i have clarified this point in the README file. I am so sorry that I do not clarify it before. It is my fault.

**Comment by ML-Song** [comment]
Why my comment has been deleted?
